name: Unzip File

on: [push, workflow_dispatch]  # รันเมื่อ push หรือกดรันเอง

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Unzip File
        run: unzip InteractiveTracker.zip -d ./
        
      - name: List Files (ตรวจสอบไฟล์)
        run: ls -la
